# Generated by Django 5.2 on 2025-05-01 17:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disponibilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidad',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
